Adding initialization headers to a WebSocket GraphQL client
graphql-dotnet/graphql-client pull request #285
Opened 2020-09-28 14:34 UTC by codewalkerdan

Not just authorization, but other headers could be added that may be required when initializing a web socket connection.
It supports adding authorization tokens

2020-10-05 20:05 UTC, sungam3r commented on src/GraphQL.Client.Abstractions.Websocket/GraphQLWebSocketRequest.cs
> +        public object Payload
breaking change

2020-10-05 20:05 UTC, sungam3r commented on src/GraphQL.Primitives/GraphQL.Primitives.csproj
> +    <Version>1.0.0</Version>
?

2020-10-05 20:06 UTC, sungam3r commented on src/GraphQL.Client/GraphQL.Client.csproj
> +    <Authors>Deinok,Alexander Rose,graphql-dotnet</Authors>
https://github.com/graphql-dotnet/graphql-client/blob/master/root.props

2020-10-05 20:08 UTC, sungam3r requested changes
These edits don't seem right to me.

2020-10-07 20:01 UTC, rose-a commented
@codewalkerdan Thanks for your contribution. I'm closing this in favor of #294, which basically does the same thing albeit keeping types and names close to the [Apollo GraphQL over WebSocket Protocol Spec](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_connection_init), which this library aims to fully implement.

2020-10-07 20:01 UTC, closed without merging

2020-10-11 19:34 UTC, codewalkerdan commented
Sorry for not replying. I have little time, but thank you for the feedback.