Update ImmutableConverter.cs
graphql-dotnet/graphql-client pull request #572
Opened 2023-06-02 11:25 UTC by JorisVanEijden

Swap properties and parameters in applicability check of ImmutableConverter. This prevents properties from being lost when they are not all represented in the contructor as parameters.

Fixes #571

2023-06-04 10:03 UTC, rose-a requested changes
Hi, thanks for your contribution! Please move the new unit test into [BaseSerializerTest](https://github.com/graphql-dotnet/graphql-client/blob/master/tests/GraphQL.Client.Serializer.Tests/BaseSerializerTest.cs), we should make sure this behavior is consistent across all serializers...

2023-06-05 06:12 UTC, JorisVanEijden commented
> Hi, thanks for your contribution! Please move the new unit test into [BaseSerializerTest](https://github.com/graphql-dotnet/graphql-client/blob/master/tests/GraphQL.Client.Serializer.Tests/BaseSerializerTest.cs), we should make sure this behavior is consistent across all serializers...

Done.

2023-06-13 06:49 UTC, rose-a commented
👍 I'll try to review it this week...

2023-09-29 07:44 UTC, rose-a approved these changes

2023-09-29 07:46 UTC, merged